version: '2.0'

services:
  wps:
    image: birdhouse/pywps-scheduler-demo
    hostname: $HOSTNAME
    networks:
      - demo
    environment:
      HOSTNAME: $HOSTNAME
      HTTP_PORT: $HTTP_PORT
      OUTPUT_PORT: $OUTPUT_PORT
    ports:
      # wps port
      - "$HTTP_PORT:$HTTP_PORT"
      # nginx output port
      - "$OUTPUT_PORT:$OUTPUT_PORT"
    volumes_from:
      # shared volume /opt/birdhouse
      - slurm
  slurm:
    hostname: slurm
    image: birdhouse/slurm
    networks:
      - demo
    # ports:
    #  - "6818:6818"
    #  - "6817:6817"
  # HINT: Unomment the following lines to mount /opt/birdhouse
  #  volumes:
  #    - /opt/birdhouse/var/lib:/opt/birdhouse/var/lib
  #    - /opt/birdhouse/var/log:/opt/birdhouse/var/log
  #    - /opt/birdhouse/etc:/opt/birdhouse/etc
  #  volume_driver: local
  db:
    hostname: db
    image: postgres
    networks:
      - demo
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    #  ports:
    #    - "5432:5432"

networks:
  demo:
