version: '2'
services:
  wps:
    image: birdhouse/pywps-scheduler-demo
    hostname: $HOSTNAME
    environment:
      HOSTNAME: $HOSTNAME
    ports:
      - "5000:5000"
    volumes_from:
      # shared volume /opt/birdhouse
      - slurm
  slurm:
    hostname: slurm
    image: birdhouse/slurm
    # ports:
    #  - "6818:6818"
    #  - "6817:6817"
  # HINT: Unomment the following lines to mount /opt/birdhouse
  #  volumes:
  #    - /opt/birdhouse/var/lib:/opt/birdhouse/var/lib
  #    - /opt/birdhouse/var/log:/opt/birdhouse/var/log
  #    - /opt/birdhouse/etc:/opt/birdhouse/etc
  #  volume_driver: local
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    #  ports:
    #    - "5432:5432"
