wps:
  image: birdhouse/pywps-scheduler-demo
  hostname: localhost
  environment:
    HOSTNAME: localhost
    HTTP_PORT: 5000
    OUTPUT_PORT: 5001
  ports:
    - "5000:5000"
    - "5001:5001"
  links:
    - slurm
  volumes_from:
    - slurm
slurm:
  hostname: slurm
  image: birdhouse/slurm
#  ports:
#    - "10022:22"
#  volumes:
#    - /opt/birdhouse/var/lib:/opt/birdhouse/var/lib
#    - /opt/birdhouse/var/log:/opt/birdhouse/var/log
#    - /opt/birdhouse/etc:/opt/birdhouse/etc
#  volume_driver: local
