wps:
  image: birdhouse/pywps-scheduler-demo
  hostname: $HOSTNAME
  environment:
    HOSTNAME: $HOSTNAME
    HTTP_PORT: $HTTP_PORT
    OUTPUT_PORT: $OUTPUT_PORT
  ports:
    # wps port
    - "$HTTP_PORT:$HTTP_PORT"
    # nginx output port
    - "$OUTPUT_PORT:$OUTPUT_PORT"
  links:
    # uses slurm port 6818 to communicate
    - slurm
  volumes_from:
    # shared volume /opt/birdhouse
    - slurm
slurm:
  hostname: slurm
  image: birdhouse/slurm
#  ports:
#    - "6818:6818"
# HINT: Unomment the following lines to mount /opt/birdhouse
#  volumes:
#    - /opt/birdhouse/var/lib:/opt/birdhouse/var/lib
#    - /opt/birdhouse/var/log:/opt/birdhouse/var/log
#    - /opt/birdhouse/etc:/opt/birdhouse/etc
#  volume_driver: local
