version: '2.0'
services:
  wps:
    image: birdhouse/pywps-scheduler-demo
    hostname: $HOSTNAME
    environment:
      HOSTNAME: $HOSTNAME
      HTTP_PORT: $HTTP_PORT
      OUTPUT_PORT: $OUTPUT_PORT
    ports:
      # wps port
      - "$HTTP_PORT:$HTTP_PORT"
      # nginx output port
      - "$OUTPUT_PORT:$OUTPUT_PORT"
    volumes:
      - lib:/opt/birdhouse/var/lib
      - log:/opt/birdhouse/var/log
  slurm:
    hostname: slurm
    image: birdhouse/slurm
    volumes:
      - lib:/opt/birdhouse/var/lib
      - log:/opt/birdhouse/var/log
  #  ports:
  #    - "6817:6817"
  #    - "6818:6818"
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    #  ports:
    #    - "5432:5432"

volumes:
  lib:
  log:
