version: '2'
services:
  wps:
    image: birdhouse/pywps-scheduler-demo
    ports:
      - "5000:5000"
  slurm:
    hostname: slurm
    image: birdhouse/slurm
    #volumes_from:
      # shared volume /home/demo
    #  - wps
    # ports:
    #  - "6818:6818"
    #  - "6817:6817"
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: testdb
    #  ports:
    #    - "5432:5432"
