emu:
  image: birdhouse/pywps-scheduler-demo
  hostname: localhost
  environment:
    HOSTNAME: localhost
  ports:
    - "8080:8080"
    - "8000:8000"
  links:
    - slurm
  volumes_from:
    - slurm
slurm:
  hostname: slurm
  image: birdhouse/slurm
#  ports:
#    - "10022:22"
#  volumes:
#    - /opt/birdhouse/var/lib:/opt/birdhouse/var/lib
#    - /opt/birdhouse/var/log:/opt/birdhouse/var/log
#    - /opt/birdhouse/etc:/opt/birdhouse/etc
#  volume_driver: local
