---
- name: Create nginx directory
  file:
    path: "{{ prefix }}/etc/nginx/conf.d"
    state: directory
    mode: 0755

- name: Copy nginx configuration
  template: src=default.conf dest={{ prefix }}/etc/nginx/conf.d/default.conf
