---
- name: Create etc/nginx directory
  file:
    path: "{{ prefix }}/etc/nginx/sites.d"
    state: directory
    mode: 0755

- name: Create var/log/nginx directory
  file:
    path: "{{ prefix }}/var/log/nginx"
    state: directory
    mode: 0755

- name: Create var/tmp/nginx directory
  file:
    path: "{{ prefix }}/var/tmp/nginx"
    state: directory
    mode: 0755

- name: Copy nginx supervisor configuration
  template: src=supervisor.conf dest={{ prefix }}/etc/supervisor/conf.d/nginx.conf

- name: Copy default nginx configuration
  copy:
    src: "{{ conda_prefix }}/etc/nginx/"
    dest: "{{ prefix }}/etc/nginx"
    mode: 0644

- name: Copy nginx configuration
  template: src=nginx.conf dest={{ prefix }}/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy nginx default configuration
  template: src=default.conf dest={{ prefix }}/etc/nginx/sites.d/default.conf
  notify: restart nginx
