---
# This playbook installs a WPS service.
# TODO: when install has failed or anaconda is broken then run make install again

- name: git clone
  git: repo=https://github.com/bird-house/emu dest="{{ src_dir }}/{{ service }}" force=yes
  register: git

- name: copy buildout configuration
  template: src=custom.cfg dest="{{ src_dir }}/{{ service }}/custom.cfg"
  register: config

- name: copy make configuration
  template: src=Makefile.config dest="{{ src_dir }}/{{ service }}/Makefile.config"
  register: config

- name: install
  shell: cd "{{ src_dir }}/{{ service }}" && make clean && make install
  notify: restart
  when: git.changed

- name: update
  shell: cd "{{ src_dir }}/{{ service }}" && make update
  notify: restart
  when: config.changed

