---
# This playbook deploys the whole birdhouse application stack in this site. 

# Apply common configuration to all hosts
- name: Prepare system
  hosts: all
  remote_user: pingu
  become: yes
  become_user: root
  roles:
    - common

# Configure and deploy WPS processing servers.
- name: Deploy processing servers
  hosts: processing
  remote_user: pingu
  become: yes
  become_user: birdhouse
  roles: 
    - emu
    - hummingbird
    - malleefowl

# Configure and deploy frontend web servers.
- name: Deploy frontend web servers
  hosts: frontend
  remote_user: pingu
  become: yes
  become_user: birdhouse
  roles: 
    - phoenix

