---
# This playbook deploys the whole birdhouse application stack in this site. 

- name: install birdhouse
  hosts: local
  remote_user: pingu
  become: yes
  become_user: birdhouse
  roles: 
    - common
    - emu
    - hummingbird
    - malleefowl
    - phoenix

