---
# This playbook installs the flyingpigeon WPS service.
# TODO: when install has failed or anaconda is broken then run make install again

- name: git clone flyingpigeon
  git: repo=https://github.com/bird-house/flyingpigeon dest=flyingpigeon force=yes
  register: git_flyingpigeon

- name: install flyingpigeon
  shell: cd flyingpigeon && make clean && make install
  notify: restart flyingpigeon
  when: git_flyingpigeon.changed

- name: copy flyingpigeon configuration
  template: src=custom.cfg dest=flyingpigeon/custom.cfg
  register: config_flyingpigeon

- name: update flyingpigeon
  shell: cd flyingpigeon && make update
  notify: restart flyingpigeon
  when: config_flyingpigeon.changed

