---
# This playbook installs the emu WPS service.

- name: git clone hummingbird
  git: repo=https://github.com/bird-house/hummingbird.git dest=hummingbird

- name: install hummingbird
  shell: cd hummingbird && make clean && make install
  notify: restart hummingbird
