---
# This playbook installs the emu WPS service.
# TODO: when install has failed or anaconda is broken then run make install again

- name: git clone hummingbird
  git: repo=https://github.com/bird-house/hummingbird dest="{{ src_dir }}/hummingbird" force=yes
  register: git_hummingbird

- name: copy buildout configuration
  template: src=custom.cfg dest="{{ src_dir }}/hummingbird/custom.cfg"
  register: config_hummingbird

- name: copy make configuration
  template: src=Makefile.config dest="{{ src_dir }}/hummingbird/Makefile.config"
  register: config_hummingbird

- name: install hummingbird
  shell: cd "{{ src_dir }}/hummingbird" && make clean && make install
  notify: restart hummingbird
  when: git_hummingbird.changed

- name: update hummingbird
  shell: cd "{{ src_dir }}/hummingbird" && make update
  notify: restart hummingbird
  when: config_hummingbird.changed

