---
- name: install slurm packages on Ubuntu/Debian
  apt: name=slurm-llnl

- name: create folders used by SLURM and set slurm owner
  file: path={{item}} state=directory owner=slurm group=slurm mode=0755
  with_items:
    - /var/spool/slurm
    - /var/log/slurm
    - /var/log/munge

- name: create slurm.conf
  template: dest=/etc/slurm-llnl/slurm.conf src=slurm.conf
  notify: restart slurm
