---
- name: Install slurm packages on Ubuntu/Debian
  apt: name=build-essential,munge,slurm-llnl

- name: Create munge key
  command: /usr/sbin/create-munge-key

- name: Create munge run folder
  file:
    path: /var/run/munge
    state: directory
    owner: munge
    group: munge
    mode: 0755

- name: Fix munge run permissions
  file:
    path: /var/log/munge
    state: directory
    mode: 0755

- name: Fix slurm log folder
  file:
    path: /var/log/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: Touch slurm job_completions
  file:
    path: /var/log/slurm/job_completions
    state: touch
    owner: slurm
    group: slurm
    mode: 0644

- name: Touch slurm accounting
  file:
    path: /var/log/slurm/accounting
    state: touch
    owner: slurm
    group: slurm
    mode: 0644

- name: Fix spool folder
  file:
    path: /var/spool
    state: directory
    owner: root
    group: slurm
    mode: 0775

- name: Touch slurm last_config_lite
  file:
    path: /var/spool/last_config_lite
    state: touch
    owner: slurm
    group: slurm
    mode: 0644

- name: Touch slurm last_config_lite.new
  file:
    path: /var/spool/last_config_lite.new
    state: touch
    owner: slurm
    group: slurm
    mode: 0644

- name: Create the slurm.conf file
  template: dest=/etc/slurm-llnl/slurm.conf src=slurm.conf.j2
  notify: restart munge
  notify: restart slurm

# - name: Create the supervisor.conf file
#   template: dest=/etc/supervisor/conf.d/slurm.conf src=supervisor.conf.j2
#   notify: restart slurm
