---
- name: install slurm packages on Debian
  apt: name=slurm-llnl
  when: ansible_os_family == "Debian"

- name: create slurm user and group
  user: name="slurm" shell=/bin/bash system=yes
  when: ansible_os_family == "RedHat"

- name: install rpm slurm packages
  yum:
    name:
      - slurm
      - slurm-plugins
      - slurm-munge
    state: present
  when: ansible_os_family == "RedHat"

- name: set SLURM facts on CentOS
  set_fact:
    SLURM_CONF: /etc/slurm/slurm.conf
    SLURM_SERVICE: slurmctld
    SLURM_DAEMON: slurmd
  when: ansible_os_family == "RedHat"

- name: set SLURM facts on Debian
  set_fact:
    SLURM_CONF: /etc/slurm-llnl/slurm.conf
    SLURM_SERVICE: slurm-llnl
    SLURM_DAEMON: slurm-llnl
  when: ansible_os_family == "Debian"

- name: create folders used by SLURM and set slurm owner
  file: path={{item}} state=directory owner=slurm group=slurm mode=0755
  with_items:
    - /var/spool/slurm
    - /var/log/slurm
    - /var/log/munge

- name: create slurm.conf
  template: dest={{SLURM_CONF}} src=slurm.conf

- name: start slurm control service
  service: name={{SLURM_SERVICE}} state=started enabled=yes

- name: start slurm daemon service
  service: name={{SLURM_DAEMON}} state=started enabled=yes
