---
- name: install slurm dependences on Debian
  apt: name=build-essential,munge,slurm-llnl

- name: create munge key
  command: /usr/sbin/create-munge-key

- name: create munge run folder
  file:
    path: /var/run/munge
    state: directory
    owner: munge
    group: munge
    mode: 0755

- name: fix munge run permissions
  file:
    path: /var/log/munge
    state: directory
    mode: 0755

- name: fix slurm log folder
  file:
    path: /var/log/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: touch slurm job_completions
  file:
    path: /var/log/slurm/job_completions
    state: touch
    owner: slurm
    group: slurm
    mode: 0644

- name: touch slurm accounting
  file:
    path: /var/log/slurm/accounting
    state: touch
    owner: slurm
    group: slurm
    mode: 0644

- name: fix spool folder
  file:
    path: /var/spool
    state: directory
    owner: root
    group: slurm
    mode: 0775

- name: touch slurm last_config_lite
  file:
    path: /var/spool/last_config_lite
    state: touch
    owner: slurm
    group: slurm
    mode: 0644

- name: touch slurm last_config_lite.new
  file:
    path: /var/spool/last_config_lite.new
    state: touch
    owner: slurm
    group: slurm
    mode: 0644
