---
# This playbook is used to install slurm.
- hosts: all
  roles:
    - common
    - role: uchida.miniconda
      miniconda_python: 2
      miniconda_prefix: /opt/anaconda
      miniconda_env:
        name: root
        dependencies:
          - python=2
          - supervisor
    - munge
    - slurm
    - drmaa
    - supervisor
