---
# This playbook installs the emu WPS service.

- name: git clone emu
  git: repo=https://github.com/bird-house/emu dest=emu force=yes

- name: install emu
  shell: cd emu && make clean && make install
  notify: restart emu
