---
# Common playbook for birdhouse apps
- name: Add group "birdhouse"
  group: name=birdhouse

- name: Add user "birdhouse"
  user: name=birdhouse group=birdhouse home=/home/birdhouse

- name: Install supervisor
  package: name=supervisor state=latest
  tags: supervisor

- name: Configure supervisor
  template: src=supervisord.conf dest=/etc/supervisor/supervisord.conf
  tags: supervisor
  notify: restart supervisor

- name: Start the supervisor service
  service: name=supervisor state=started enabled=yes
  tags: supervisor
